name: Code Review

on:
  workflow_call:  # 允许其他仓库调用这个 Workflow
    secrets:
      LLM_API_KEY:
        required: true
      LLM_API_URL:
        required: true
      THIS_GITHUB_TOKEN:
        required: true
      REPOSITORY_NAME:
        required: true
      REPOSITORY_OWNER:
        required: true
      PROMPT_LEVEL:
        required: true
  pull_request:
    types: [opened, synchronize, reopened]  # 触发条件：PR 创建/更新/重新打开

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Change Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name:  Checkout AI Code Reviewer Code
        uses: actions/checkout@v4
        with:
          repository: exampler0906/ai_reviewer
          token: ${{ secrets.THIS_GITHUB_TOKEN }}  # 需要有权限的 Token
          ref: main
      
      - name: Set Python Version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Set Pip Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirement
        run: |
          python -m pip install --upgrade pip
          ls ../
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pip install -r requirements.txt
          elif [[ -n "${{ github.workflow_ref }}" ]]; then
            pip install -r ai_reviewer/requirements.txt
          fi

      - name: Code Review
        env:
            LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
            LLM_API_URL: ${{ secrets.LLM_API_URL }}
            GITHUB_TOKEN: ${{ secrets.THIS_GITHUB_TOKEN }}
            REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
            REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}
            PROMPT_LEVEL : ${{ secrets.PROMPT_LEVEL }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           cd src
           echo "LOG_PATH=src/app.log" >> $GITHUB_ENV
          elif [[ -n "${{ github.workflow_ref }}" ]]; then
            cd ai_reviewer/src
            echo "LOG_PATH=ai_reviewer/src/app.log" >> $GITHUB_ENV
          fi
          python ai_code_reviewer.py ${{ github.event.pull_request.number }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload log
          path: ${{ env.LOG_PATH }}
          working-directory: ./
          retention-days: 1
